### ISSUE TITLE
Add support for built-in getenv and putenv php commands

### ISSUE THREAD

**Issue by AaronHolbrook** [arrilot/dotenv-php#1]
Would love to have utilization of the built-in `getenv` functionality as I cannot be sure in all cases that your package is loaded (if I'm distributing my own package for instance).

You could iterate all values that are passed and load them in yourself via `putenv`.

Let me know if a pull request would be helpful; something like: 

![](http://d.pr/i/urCrtp/3IHK2lj0+)

**Comment by arrilot** [comment]
So, you propose to add a method (e.g `DotEnv::sendToPutEnv()`) that passes every variable loaded by the package to `putenv()`, am I right?

**Comment by AaronHolbrook** [comment]
Something like that.

The end result should be, I should be able to use the php built in functions to retrieve the env variables, not this package's methods.

**Comment by arrilot** [comment]
Here we go https://github.com/arrilot/dotenv-php/commit/a42a07d3d81672a1ed23545465927502d72d0ca2

**Comment by AaronHolbrook** [comment]
Awesome @arrilot ! Thanks so much!
